### ISSUE TITLE
Задача 1. Создать файл INFO.md, скопировать в него случайный текст

### ISSUE THREAD

**Issue by Smazhko** [sem3-3-3/sem-3-3-3#5]
Задача 1. Создать файл [INFO.md](http://info.md/), скопировать в него случайный текст

**Comment by Kochengui** [comment]
ОК, приступаю к выполнению!

**Comment by Kochengui** [comment]
все норм? @Smazhko

**Comment by Smazhko** [comment]
да, @Kochengui, отлично !
